all:
	(cd helloworld && $(MAKE))
	(cd stars && cd build && $(MAKE))
	(cd pictures && cd build && $(MAKE))
	(cd movetable && cd build && $(MAKE))
	
clean:
	(cd helloworld && $(MAKE) clean)
	(cd stars && cd build && $(MAKE) clean)
	(cd pictures && cd build && $(MAKE) clean)
	(cd movetable && cd build && $(MAKE) clean)