all:
	(cd helloworld && $(MAKE))
	(cd stars && cd build && $(MAKE))
	(cd picture && cd build && $(MAKE))
	(cd movetable && cd build && $(MAKE))
	(cd hellodemo && cd build && $(MAKE))
	
clean:
	(cd helloworld && $(MAKE) clean)
	(cd stars && cd build && $(MAKE) clean)
	(cd picture && cd build && $(MAKE) clean)
	(cd movetable && cd build && $(MAKE) clean)
	(cd hellodemo && cd build && $(MAKE) clean)
